const judul = "level 1 -TASK 1";
console.log(judul);
const nama = "PUTRI MAYANGSARI";
console.log(nama);
const umur = 27;
console.log(umur);
const alamat = "Jl.Sunan Giri No.137, Simpang Tiga Sipin, Kota Baru, Kota Jambi.";
console.log(alamat);
const hobi = "membaca, menulis, mendengar murottal.";
console.log(hobi);
const sekolah = "SMA Islam Al-Falah Jambi.";
console.log(sekolah);
const TertarikProgramming = "Mengapa programming? Sejak kecil memang sudah tertarik akan dunia IT, mulai mengotak-atik laptop dengan mengganti kursornya, themenya, membuat wordpress blog dan mengeditnya (sayangnya, blog sudah saya hapus), dan sebagainya.";
console.log(TertarikProgramming);
const PembelajaranProgramming = "Html, Css, VueJs, MySQL, R. Masih memerlukan pembelajaran yang lebih.";
console.log(PembelajaranProgramming);
const Kesulitan = "Pernah mengalami kesulitan, bahkan sering. Kadang saat mencari referensi pun masih merasa kesulitan, serupa pola codenya tapi code saya perlu penyesuaian sehingga saya sedikit memakan waktu untuk menemukan code yang cocok.";
console.log(Kesulitan);
const BootcampFazztrack = "Saya lihat ads Fazztrack tengah malam, tertulis disalurkan kerja (menjanjikan nih), dan saya pun sedang cari pekerjaan di dunia ini (programming).";
console.log(BootcampFazztrack);
const KenapaSaya = "Saya ingin lebih mengenal dunia programming, bisa fast learner.";
console.log(KenapaSaya);